<?php

namespace Database\Seeders;

use App\Models\FabricType;
use App\Support\FabricProfile;
use Illuminate\Database\Seeder;

/**
 * بانک پایه پارچه.
 *
 * هر ردیف یک «شناسنامه» کامل است: ترکیب الیاف، مشخصات فیزیکی، راهنمای نگهداری و
 * پیشنهاد دوخت. کاربر با انتخاب یکی از این‌ها همه مشخصات را یک‌جا می‌گیرد و لازم
 * نیست هیچ عدد فنی وارد کند. با اجرای دوباره، ردیف‌ها روی کد پارچه به‌روز می‌شوند.
 */
class FabricTypeSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->rows() as $index => $row) {
            FabricType::updateOrCreate(['code' => $row['code']], [
                'name_fa' => $row['name_fa'],
                'name_en' => $row['name_en'],
                'category' => $row['category'],
                'family' => $row['family'],
                'fiber_composition' => $row['fibers'],
                'profile' => FabricProfile::make($row['profile'])->toArray(),
                'care' => $row['care'],
                'sewing' => $row['sewing'],
                'description' => $row['description'],
                'sort' => ($index + 1) * 10,
                'is_active' => true,
            ]);
        }
    }

    /** @return array<int, array<string, mixed>> */
    protected function rows(): array
    {
        return [
            // ——— پنبه و نخی ———
            [
                'code' => 'cotton-poplin',
                'name_fa' => 'پوپلین نخی',
                'name_en' => 'Cotton Poplin',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 120, 'thickness_mm' => 0.35, 'drape' => 0.4, 'stiffness' => 0.45,
                    'stretch_warp' => 0, 'stretch_weft' => 0, 'stretch_bias' => 12, 'recovery' => 55,
                    'transparency' => 0.08, 'sheen' => 0.2, 'roughness' => 0.35,
                    'shrinkage' => 3, 'breathability' => 0.85, 'warmth' => 0.3,
                    'moisture_absorption' => 0.75, 'wrinkle_resistance' => 0.35,
                    'fraying' => 0.35, 'curling' => 0.05, 'slippage' => 0.15, 'distortion' => 0.15,
                    'heat_sensitivity' => 0.15, 'steam_sensitivity' => 0.1, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی گرم تا ۱۸۰ درجه با بخار', 'dryer' => 'خشک‌کن ملایم؛ کمی آب می‌رود'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ یا ۸۰/۱۲ نوک تیز', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز یا زیگزاگ', 'tip' => 'پیش از برش یک بار بشویید تا بعد از دوخت آب نرود.'],
                'description' => 'پارچه نخی صاف و خنک با بافت فشرده؛ بهترین انتخاب برای پیراهن، شومیز و لباس بچه. رام است و برای تازه‌کارها عالی است.',
            ],
            [
                'code' => 'cotton-plain',
                'name_fa' => 'نخی ساده (متقال)',
                'name_en' => 'Plain Cotton (Calico)',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 145, 'thickness_mm' => 0.42, 'drape' => 0.35, 'stiffness' => 0.5,
                    'stretch_bias' => 12, 'recovery' => 50, 'transparency' => 0.06, 'sheen' => 0.1,
                    'roughness' => 0.45, 'shrinkage' => 4.5, 'breathability' => 0.85, 'warmth' => 0.35,
                    'moisture_absorption' => 0.8, 'wrinkle_resistance' => 0.3,
                    'fraying' => 0.4, 'slippage' => 0.12, 'distortion' => 0.15,
                    'heat_sensitivity' => 0.12, 'steam_sensitivity' => 0.1, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین، آب ۴۰ درجه', 'iron' => 'اتوی گرم با بخار', 'dryer' => 'مجاز؛ حتماً یک بار پیش‌شور کنید'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'برای الگوی آزمایشی (مولاژ) ارزان‌ترین و بهترین گزینه است.'],
                'description' => 'نخی خام و ارزان با بافت ساده؛ برای دوخت آزمایشی، آستر ضخیم و کارهای خانه. آب‌رفت بالایی دارد.',
            ],
            [
                'code' => 'cotton-twill',
                'name_fa' => 'توییل نخی',
                'name_en' => 'Cotton Twill',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 98], ['name' => 'الاستان', 'percent' => 2]],
                'profile' => [
                    'weight_gsm' => 245, 'thickness_mm' => 0.65, 'drape' => 0.28, 'stiffness' => 0.6,
                    'stretch_weft' => 10, 'stretch_bias' => 15, 'recovery' => 80,
                    'transparency' => 0.02, 'sheen' => 0.15, 'roughness' => 0.5,
                    'shrinkage' => 3.5, 'breathability' => 0.7, 'warmth' => 0.5,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.55,
                    'fraying' => 0.4, 'slippage' => 0.1, 'distortion' => 0.15,
                    'heat_sensitivity' => 0.15, 'steam_sensitivity' => 0.1, 'directional' => true, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی گرم با بخار', 'dryer' => 'ملایم'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک راسته ۳ میلی‌متر', 'seam' => 'سردوز یا درز دوبل', 'tip' => 'بافت مورب دارد؛ جهت بافت را در همه قطعات یکسان بگیرید.'],
                'description' => 'نخی محکم با بافت مورب؛ برای شلوار، مانتو، جیب و کار روزمره. فرم را خوب نگه می‌دارد.',
            ],
            [
                'code' => 'cotton-sateen',
                'name_fa' => 'ساتن نخی',
                'name_en' => 'Cotton Sateen',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 97], ['name' => 'الاستان', 'percent' => 3]],
                'profile' => [
                    'weight_gsm' => 185, 'thickness_mm' => 0.45, 'drape' => 0.55, 'stiffness' => 0.3,
                    'stretch_weft' => 12, 'stretch_bias' => 18, 'recovery' => 85,
                    'transparency' => 0.05, 'sheen' => 0.55, 'roughness' => 0.15,
                    'shrinkage' => 3, 'breathability' => 0.7, 'warmth' => 0.4,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.5,
                    'fraying' => 0.35, 'slippage' => 0.3, 'distortion' => 0.2,
                    'heat_sensitivity' => 0.2, 'steam_sensitivity' => 0.15, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه، پشت‌ورو', 'iron' => 'اتو از پشت پارچه', 'dryer' => 'ملایم'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'براقی سطح جهت‌دار است؛ همه قطعات را یک‌جهت بچینید.'],
                'description' => 'نخی با سطح براق و لمس نرم؛ برای پیراهن مجلسی راحت، دامن و روبالشی.',
            ],
            [
                'code' => 'cotton-sheeting',
                'name_fa' => 'ملحفه‌ای',
                'name_en' => 'Sheeting',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 50], ['name' => 'پلی‌استر', 'percent' => 50]],
                'profile' => [
                    'weight_gsm' => 130, 'thickness_mm' => 0.35, 'drape' => 0.45, 'stiffness' => 0.4,
                    'stretch_bias' => 12, 'recovery' => 70, 'transparency' => 0.1, 'sheen' => 0.25,
                    'roughness' => 0.3, 'shrinkage' => 2, 'breathability' => 0.65, 'warmth' => 0.35,
                    'moisture_absorption' => 0.45, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.35, 'slippage' => 0.2, 'heat_sensitivity' => 0.45, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین، آب ۴۰ درجه', 'iron' => 'اتوی متوسط', 'dryer' => 'مجاز'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'عرض زیاد این پارچه (۲۴۰ سانتی‌متر) برای قطعات بزرگ صرفه دارد.'],
                'description' => 'پارچه پهن نخی-پلی‌استر برای ملحفه، روتختی و روپوش؛ کم چین می‌خورد و کم آب می‌رود.',
            ],
            [
                'code' => 'cotton-thread-blend',
                'name_fa' => 'نخ‌پنبه',
                'name_en' => 'Cotton-Poly Blend',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 65], ['name' => 'پلی‌استر', 'percent' => 35]],
                'profile' => [
                    'weight_gsm' => 155, 'thickness_mm' => 0.4, 'drape' => 0.45, 'stiffness' => 0.4,
                    'stretch_bias' => 14, 'recovery' => 72, 'transparency' => 0.08, 'sheen' => 0.25,
                    'roughness' => 0.35, 'shrinkage' => 2, 'breathability' => 0.7, 'warmth' => 0.4,
                    'moisture_absorption' => 0.5, 'wrinkle_resistance' => 0.65,
                    'fraying' => 0.35, 'slippage' => 0.2, 'heat_sensitivity' => 0.45, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین، آب ۴۰ درجه', 'iron' => 'اتوی متوسط با بخار', 'dryer' => 'مجاز'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'میان‌راه خوبی است: خنکی نخ با کم‌چین‌خوردگی پلی‌استر.'],
                'description' => 'ترکیب پرمصرف بازار برای مانتو اداری، روپوش و لباس فرم؛ اتوپذیر و کم‌دردسر.',
            ],

            // ——— کتان و کنف ———
            [
                'code' => 'linen',
                'name_fa' => 'کتان (لینن)',
                'name_en' => 'Linen',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'کتان', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 190, 'thickness_mm' => 0.5, 'drape' => 0.45, 'stiffness' => 0.55,
                    'stretch_bias' => 10, 'recovery' => 40, 'transparency' => 0.15, 'sheen' => 0.25,
                    'roughness' => 0.7, 'shrinkage' => 5, 'breathability' => 0.95, 'warmth' => 0.2,
                    'moisture_absorption' => 0.9, 'wrinkle_resistance' => 0.15,
                    'fraying' => 0.6, 'slippage' => 0.2, 'distortion' => 0.25,
                    'heat_sensitivity' => 0.15, 'steam_sensitivity' => 0.1, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه، دور کم', 'iron' => 'اتوی داغ با بخار زیاد و پارچه کمی نمناک', 'dryer' => 'بهتر است در سایه خشک شود'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز یا درز فرانسوی', 'tip' => 'لبه‌ها زیاد ریش می‌شود؛ بلافاصله پس از برش درزها را تمیز کنید.'],
                'description' => 'خنک‌ترین پارچه تابستانی با بافت طبیعی؛ زیبا چین می‌خورد و همین جذابیت آن است. آب‌رفت بالا دارد.',
            ],
            [
                'code' => 'linen-viscose',
                'name_fa' => 'کتان ویسکوز',
                'name_en' => 'Linen-Viscose',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'کتان', 'percent' => 55], ['name' => 'ویسکوز', 'percent' => 45]],
                'profile' => [
                    'weight_gsm' => 165, 'thickness_mm' => 0.45, 'drape' => 0.62, 'stiffness' => 0.35,
                    'stretch_bias' => 16, 'recovery' => 55, 'transparency' => 0.14, 'sheen' => 0.35,
                    'roughness' => 0.45, 'shrinkage' => 4, 'breathability' => 0.85, 'warmth' => 0.25,
                    'moisture_absorption' => 0.85, 'wrinkle_resistance' => 0.4,
                    'fraying' => 0.5, 'slippage' => 0.35, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.3, 'steam_sensitivity' => 0.25, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی متوسط با بخار', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'نرم‌تر و لخت‌تر از کتان خالص است؛ برای پیراهن بلند مناسب‌تر است.'],
                'description' => 'کتان با ریزش نرم‌تر و چین‌خوردگی کمتر؛ برای مانتو تابستانی، پیراهن بلند و شلوار راحتی.',
            ],
            [
                'code' => 'hemp',
                'name_fa' => 'کنف',
                'name_en' => 'Hemp',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'کنف', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 255, 'thickness_mm' => 0.7, 'drape' => 0.3, 'stiffness' => 0.65,
                    'stretch_bias' => 8, 'recovery' => 40, 'transparency' => 0.06, 'sheen' => 0.15,
                    'roughness' => 0.85, 'shrinkage' => 5, 'breathability' => 0.9, 'warmth' => 0.35,
                    'moisture_absorption' => 0.85, 'wrinkle_resistance' => 0.25,
                    'fraying' => 0.55, 'slippage' => 0.1, 'heat_sensitivity' => 0.15, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی داغ با بخار', 'dryer' => 'خشک شدن در هوای آزاد'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک راسته ۳ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'بار اول زبر است اما با هر شست‌وشو نرم‌تر می‌شود.'],
                'description' => 'الیاف بسیار مقاوم و طبیعی؛ برای کیف، رومیزی، پیراهن روستیک و لباس کار.',
            ],
            [
                'code' => 'bamboo',
                'name_fa' => 'بامبو',
                'name_en' => 'Bamboo',
                'category' => 'natural',
                'family' => 'knit',
                'fibers' => [['name' => 'بامبو', 'percent' => 95], ['name' => 'الاستان', 'percent' => 5]],
                'profile' => [
                    'weight_gsm' => 175, 'thickness_mm' => 0.6, 'drape' => 0.8, 'stiffness' => 0.15,
                    'stretch_warp' => 12, 'stretch_weft' => 35, 'stretch_bias' => 40, 'recovery' => 88,
                    'transparency' => 0.15, 'sheen' => 0.4, 'roughness' => 0.08,
                    'shrinkage' => 4, 'breathability' => 0.9, 'warmth' => 0.35,
                    'moisture_absorption' => 0.9, 'wrinkle_resistance' => 0.6,
                    'fraying' => 0.1, 'curling' => 0.55, 'slippage' => 0.45, 'distortion' => 0.45,
                    'heat_sensitivity' => 0.45, 'steam_sensitivity' => 0.4, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۵/۱۱ نوک گرد', 'stitch' => 'کوک کشی یا زیگزاگ باریک', 'seam' => 'سردوز', 'tip' => 'موقع دوخت پارچه را نکشید؛ درز موجی می‌شود.'],
                'description' => 'کشباف بسیار نرم و خنک با جذب رطوبت بالا؛ برای تی‌شرت، لباس زیر و لباس بچه.',
            ],

            // ——— پشم و کشمیر ———
            [
                'code' => 'wool-gabardine',
                'name_fa' => 'گاباردین',
                'name_en' => 'Wool Gabardine',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پشم', 'percent' => 55], ['name' => 'پلی‌استر', 'percent' => 43], ['name' => 'الاستان', 'percent' => 2]],
                'profile' => [
                    'weight_gsm' => 280, 'thickness_mm' => 0.8, 'drape' => 0.32, 'stiffness' => 0.6,
                    'stretch_weft' => 8, 'stretch_bias' => 18, 'recovery' => 82,
                    'transparency' => 0.02, 'sheen' => 0.2, 'roughness' => 0.4,
                    'shrinkage' => 2, 'breathability' => 0.6, 'warmth' => 0.7,
                    'moisture_absorption' => 0.5, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.4, 'slippage' => 0.2, 'distortion' => 0.2,
                    'heat_sensitivity' => 0.5, 'steam_sensitivity' => 0.45, 'directional' => true, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'خشک‌شویی؛ در صورت لزوم با دست و آب سرد', 'iron' => 'اتوی متوسط از پشت با پارچه محافظ', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک راسته ۳ میلی‌متر', 'seam' => 'سردوز یا نواردوزی', 'tip' => 'با بخار زیاد فرم می‌گیرد، اما اتوی مستقیم برق می‌اندازد.'],
                'description' => 'پارچه رسمی و فرم‌گیر با بافت مورب ریز؛ استاندارد مانتو اداری، کت و شلوار پارچه‌ای.',
            ],
            [
                'code' => 'wool-crepe',
                'name_fa' => 'کرپ پشمی',
                'name_en' => 'Wool Crepe',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پشم', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 220, 'thickness_mm' => 0.6, 'drape' => 0.7, 'stiffness' => 0.25,
                    'stretch_bias' => 22, 'recovery' => 78, 'transparency' => 0.05, 'sheen' => 0.15,
                    'roughness' => 0.55, 'shrinkage' => 3, 'breathability' => 0.7, 'warmth' => 0.65,
                    'moisture_absorption' => 0.6, 'wrinkle_resistance' => 0.8,
                    'fraying' => 0.45, 'slippage' => 0.3, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.55, 'steam_sensitivity' => 0.5, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'خشک‌شویی', 'iron' => 'اتوی ملایم با پارچه محافظ', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک راسته ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'پیش از دوخت لبه‌ها را با لایی نواری تثبیت کنید تا کشیده نشود.'],
                'description' => 'پشم با سطح دانه‌دار و ریزش زیبا؛ برای دامن، شلوار پارچه‌ای و کت زنانه.',
            ],
            [
                'code' => 'wool-flannel',
                'name_fa' => 'فلانل پشمی',
                'name_en' => 'Wool Flannel',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پشم', 'percent' => 70], ['name' => 'ویسکوز', 'percent' => 30]],
                'profile' => [
                    'weight_gsm' => 310, 'thickness_mm' => 1.2, 'drape' => 0.4, 'stiffness' => 0.45,
                    'stretch_bias' => 20, 'recovery' => 75, 'transparency' => 0.01, 'sheen' => 0.1,
                    'roughness' => 0.3, 'shrinkage' => 3, 'breathability' => 0.55, 'warmth' => 0.85,
                    'moisture_absorption' => 0.6, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.35, 'slippage' => 0.25, 'distortion' => 0.25,
                    'heat_sensitivity' => 0.55, 'steam_sensitivity' => 0.5,
                    'has_nap' => true, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'خشک‌شویی', 'iron' => 'اتوی ملایم از پشت، بدون فشار', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک راسته ۳ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'خواب‌دار است؛ همه قطعات را یک‌جهت بچینید.'],
                'description' => 'پشم پرزدار و گرم؛ برای پالتو سبک، شلوار زمستانی و دامن مدادی.',
            ],
            [
                'code' => 'cashmere',
                'name_fa' => 'کشمیر',
                'name_en' => 'Cashmere',
                'category' => 'natural',
                'family' => 'knit',
                'fibers' => [['name' => 'کشمیر', 'percent' => 90], ['name' => 'پشم مرینو', 'percent' => 10]],
                'profile' => [
                    'weight_gsm' => 250, 'thickness_mm' => 1.4, 'drape' => 0.72, 'stiffness' => 0.12,
                    'stretch_warp' => 15, 'stretch_weft' => 25, 'stretch_bias' => 35, 'recovery' => 80,
                    'transparency' => 0.05, 'sheen' => 0.2, 'roughness' => 0.05,
                    'shrinkage' => 4, 'breathability' => 0.7, 'warmth' => 0.95,
                    'moisture_absorption' => 0.65, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.15, 'curling' => 0.4, 'slippage' => 0.4, 'distortion' => 0.5,
                    'heat_sensitivity' => 0.6, 'steam_sensitivity' => 0.55, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی با شامپو مخصوص و آب سرد', 'iron' => 'فقط بخار از فاصله', 'dryer' => 'خشک‌کن ممنوع؛ روی حوله پهن کنید'],
                'sewing' => ['needle' => 'سوزن ۷۵/۱۱ نوک گرد', 'stitch' => 'کوک کشی بلند ۳ میلی‌متر', 'seam' => 'سردوز سبک یا کوک دستی', 'tip' => 'زیر پایه چرخ کاغذ نازک بگذارید تا پارچه کشیده نشود.'],
                'description' => 'گران‌ترین و گرم‌ترین الیاف حیوانی با لمس بی‌نظیر؛ برای شال، پلیور و کت نرم.',
            ],

            // ——— ابریشم و پارچه‌های مجلسی ———
            [
                'code' => 'silk-habotai',
                'name_fa' => 'حریر (ابریشم)',
                'name_en' => 'Silk Habotai',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'ابریشم', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 60, 'thickness_mm' => 0.12, 'drape' => 0.95, 'stiffness' => 0.05,
                    'stretch_warp' => 0, 'stretch_weft' => 0, 'stretch_bias' => 30, 'recovery' => 60,
                    'transparency' => 0.6, 'sheen' => 0.7, 'roughness' => 0.05,
                    'shrinkage' => 3, 'breathability' => 0.85, 'warmth' => 0.3,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.3,
                    'fraying' => 0.75, 'curling' => 0.1, 'slippage' => 0.95, 'distortion' => 0.6,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.6, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی با آب سرد و شامپو ملایم', 'iron' => 'اتوی ملایم ۱۱۰ درجه، بدون بخار، از پشت', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۶۰/۸ میکروتکس', 'stitch' => 'کوک ریز ۲ میلی‌متر', 'seam' => 'درز فرانسوی ۱.۵ سانتی‌متر', 'tip' => 'زیر پارچه کاغذ پوستی بگذارید و با سوزن‌های ریز و نزدیک به هم سنجاق کنید.'],
                'description' => 'ابریشم نازک و بسیار لخت با ریزش آب‌گونه؛ برای شال، آستر مجلسی، بلوز و لباس شب. زیر قیچی سر می‌خورد و کار با آن مهارت می‌خواهد.',
            ],
            [
                'code' => 'silk-satin',
                'name_fa' => 'ساتن ابریشم',
                'name_en' => 'Silk Satin',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'ابریشم', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 95, 'thickness_mm' => 0.22, 'drape' => 0.9, 'stiffness' => 0.08,
                    'stretch_bias' => 28, 'recovery' => 62, 'transparency' => 0.22, 'sheen' => 0.95,
                    'roughness' => 0.03, 'shrinkage' => 3, 'breathability' => 0.75, 'warmth' => 0.35,
                    'moisture_absorption' => 0.65, 'wrinkle_resistance' => 0.35,
                    'fraying' => 0.7, 'slippage' => 0.9, 'distortion' => 0.55,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.6, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'خشک‌شویی یا شست‌وشوی دستی با آب سرد', 'iron' => 'اتوی ملایم از پشت، بدون بخار', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۶۵/۹ میکروتکس', 'stitch' => 'کوک ۲ میلی‌متر', 'seam' => 'درز فرانسوی', 'tip' => 'هر سوراخ سوزن روی ساتن می‌ماند؛ اول روی تکه اضافه امتحان کنید.'],
                'description' => 'رویه بسیار براق و پشت مات با ریزش سنگین؛ انتخاب اصلی لباس عروس، لباس شب و آستر لوکس.',
            ],
            [
                'code' => 'satin-poly',
                'name_fa' => 'ساتن (پلی‌استر)',
                'name_en' => 'Polyester Satin',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 110, 'thickness_mm' => 0.25, 'drape' => 0.82, 'stiffness' => 0.15,
                    'stretch_bias' => 22, 'recovery' => 75, 'transparency' => 0.2, 'sheen' => 0.9,
                    'roughness' => 0.05, 'shrinkage' => 1, 'breathability' => 0.25, 'warmth' => 0.4,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.8,
                    'fraying' => 0.65, 'slippage' => 0.85, 'distortion' => 0.45,
                    'heat_sensitivity' => 0.8, 'steam_sensitivity' => 0.6, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم با آب سرد', 'iron' => 'اتوی خیلی ملایم؛ حرارت زیاد پارچه را ذوب می‌کند', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ میکروتکس', 'stitch' => 'کوک ۲ میلی‌متر', 'seam' => 'درز فرانسوی یا سردوز ریز', 'tip' => 'زیر پارچه کاغذ بگذارید؛ بسیار سر می‌خورد.'],
                'description' => 'جانشین ارزان ساتن ابریشم با براقی بیشتر؛ برای لباس مجلسی، آستر و پرده.',
            ],
            [
                'code' => 'chiffon',
                'name_fa' => 'شیفون',
                'name_en' => 'Chiffon',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 42, 'thickness_mm' => 0.08, 'drape' => 0.93, 'stiffness' => 0.06,
                    'stretch_bias' => 25, 'recovery' => 70, 'transparency' => 0.8, 'sheen' => 0.25,
                    'roughness' => 0.2, 'shrinkage' => 1, 'breathability' => 0.6, 'warmth' => 0.15,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.8, 'slippage' => 0.92, 'distortion' => 0.7,
                    'heat_sensitivity' => 0.75, 'steam_sensitivity' => 0.6, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی یا کیسه توری با آب سرد', 'iron' => 'اتوی خیلی ملایم با پارچه محافظ', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۶۰/۸', 'stitch' => 'کوک ریز ۱.۸ میلی‌متر', 'seam' => 'درز فرانسوی', 'tip' => 'روی کاغذ پوستی برش بزنید و لب برگردان را باریک (۱ سانتی‌متر) بگیرید.'],
                'description' => 'توری‌مانند، بسیار سبک و شفاف با ریزش عالی؛ برای شال، آستین و روی‌لباس مجلسی. همیشه آستر لازم دارد.',
            ],
            [
                'code' => 'crepe',
                'name_fa' => 'کرپ',
                'name_en' => 'Crepe',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 95], ['name' => 'الاستان', 'percent' => 5]],
                'profile' => [
                    'weight_gsm' => 135, 'thickness_mm' => 0.4, 'drape' => 0.78, 'stiffness' => 0.18,
                    'stretch_weft' => 12, 'stretch_bias' => 25, 'recovery' => 85,
                    'transparency' => 0.12, 'sheen' => 0.15, 'roughness' => 0.45,
                    'shrinkage' => 1.5, 'breathability' => 0.4, 'warmth' => 0.35,
                    'moisture_absorption' => 0.15, 'wrinkle_resistance' => 0.85,
                    'fraying' => 0.5, 'slippage' => 0.5, 'distortion' => 0.35,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.5, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی ملایم از پشت', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'سطح دانه‌دارش اتوی مستقیم را نشان می‌دهد؛ از پشت اتو کنید.'],
                'description' => 'پرکاربردترین پارچه مانتو و پیراهن مجلسی؛ لخت، مات و تقریباً بی‌چین.',
            ],
            [
                'code' => 'crepe-maserati',
                'name_fa' => 'کرپ مازراتی',
                'name_en' => 'Maserati Crepe',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 88], ['name' => 'ویسکوز', 'percent' => 8], ['name' => 'الاستان', 'percent' => 4]],
                'profile' => [
                    'weight_gsm' => 205, 'thickness_mm' => 0.55, 'drape' => 0.65, 'stiffness' => 0.3,
                    'stretch_weft' => 18, 'stretch_bias' => 28, 'recovery' => 88,
                    'transparency' => 0.04, 'sheen' => 0.2, 'roughness' => 0.4,
                    'shrinkage' => 1.5, 'breathability' => 0.4, 'warmth' => 0.5,
                    'moisture_absorption' => 0.2, 'wrinkle_resistance' => 0.85,
                    'fraying' => 0.4, 'slippage' => 0.35, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.65, 'steam_sensitivity' => 0.5, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'کشسانی عرضی دارد؛ آزادی دور سینه را دو سانتی‌متر کمتر بگیرید.'],
                'description' => 'کرپ ضخیم و کشی بازار ایران؛ برای مانتو، کت و شلوار زنانه و مجلسی روزانه. فرم بدن را نگه می‌دارد.',
            ],
            [
                'code' => 'maserati',
                'name_fa' => 'مازراتی',
                'name_en' => 'Maserati',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 180, 'thickness_mm' => 0.5, 'drape' => 0.6, 'stiffness' => 0.35,
                    'stretch_weft' => 6, 'stretch_bias' => 20, 'recovery' => 80,
                    'transparency' => 0.03, 'sheen' => 0.2, 'roughness' => 0.35,
                    'shrinkage' => 1.5, 'breathability' => 0.35, 'warmth' => 0.5,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.9,
                    'fraying' => 0.4, 'slippage' => 0.3, 'heat_sensitivity' => 0.7, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'مجاز با دمای کم'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'تقریباً چین نمی‌خورد؛ برای لباس فرم و مانتو اداری صرفه‌جو است.'],
                'description' => 'پارچه مات و فرم‌دار با مقاومت بالا در برابر چین‌خوردگی؛ کاربرد اصلی: مانتو و لباس فرم.',
            ],
            [
                'code' => 'organza',
                'name_fa' => 'ارگانزا',
                'name_en' => 'Organza',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 48, 'thickness_mm' => 0.1, 'drape' => 0.15, 'stiffness' => 0.85,
                    'stretch_bias' => 12, 'recovery' => 75, 'transparency' => 0.75, 'sheen' => 0.5,
                    'roughness' => 0.5, 'shrinkage' => 1, 'breathability' => 0.7, 'warmth' => 0.1,
                    'moisture_absorption' => 0.05, 'wrinkle_resistance' => 0.6,
                    'fraying' => 0.7, 'slippage' => 0.6, 'distortion' => 0.4,
                    'heat_sensitivity' => 0.8, 'steam_sensitivity' => 0.7, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی با آب سرد', 'iron' => 'اتوی خیلی ملایم با پارچه محافظ', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۶۰/۸', 'stitch' => 'کوک ریز ۲ میلی‌متر', 'seam' => 'درز فرانسوی', 'tip' => 'ایستایی‌اش را برای حجم دادن به آستین و دامن به کار بگیرید.'],
                'description' => 'شفاف اما ایستا و پرحجم؛ برای آستین پفی، دامن حجم‌دار، رویه لباس عروس و تزئین.',
            ],
            [
                'code' => 'tulle',
                'name_fa' => 'تور',
                'name_en' => 'Tulle',
                'category' => 'synthetic',
                'family' => 'lace',
                'fibers' => [['name' => 'نایلون', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 28, 'thickness_mm' => 0.15, 'drape' => 0.35, 'stiffness' => 0.5,
                    'stretch_weft' => 10, 'stretch_bias' => 30, 'recovery' => 80,
                    'transparency' => 0.9, 'sheen' => 0.3, 'roughness' => 0.55,
                    'shrinkage' => 1, 'breathability' => 0.95, 'warmth' => 0.1,
                    'moisture_absorption' => 0.05, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.02, 'slippage' => 0.55, 'distortion' => 0.35,
                    'heat_sensitivity' => 0.85, 'steam_sensitivity' => 0.7, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی ملایم', 'iron' => 'اتو نکنید؛ فقط بخار از فاصله', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'درز باز بدون تمیزکاری', 'tip' => 'لبه‌اش ریش نمی‌شود؛ لازم نیست تو بگذارید.'],
                'description' => 'توری مشبک و سبک؛ برای دامن پفی، تور عروس، لایه‌های حجم‌دهنده و تزئین.',
            ],
            [
                'code' => 'lace',
                'name_fa' => 'دانتل',
                'name_en' => 'Lace',
                'category' => 'synthetic',
                'family' => 'lace',
                'fibers' => [['name' => 'نایلون', 'percent' => 90], ['name' => 'الاستان', 'percent' => 10]],
                'profile' => [
                    'weight_gsm' => 95, 'thickness_mm' => 0.4, 'drape' => 0.68, 'stiffness' => 0.25,
                    'stretch_weft' => 20, 'stretch_bias' => 35, 'recovery' => 85,
                    'transparency' => 0.7, 'sheen' => 0.35, 'roughness' => 0.5,
                    'shrinkage' => 1.5, 'breathability' => 0.85, 'warmth' => 0.2,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.25, 'curling' => 0.2, 'slippage' => 0.5, 'distortion' => 0.4,
                    'heat_sensitivity' => 0.75, 'steam_sensitivity' => 0.6, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی در کیسه توری', 'iron' => 'اتوی ملایم روی حوله', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ نوک گرد', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'نواردوزی یا درز باریک', 'tip' => 'لبه گل‌دار دانتل را به‌جای لب برگردان به کار ببرید.'],
                'description' => 'توری گل‌دار با یک لبه تزئینی؛ برای یقه، آستین، رویه بالاتنه و لباس مجلسی.',
            ],
            [
                'code' => 'guipure',
                'name_fa' => 'گیپور',
                'name_en' => 'Guipure',
                'category' => 'synthetic',
                'family' => 'lace',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 165, 'thickness_mm' => 0.7, 'drape' => 0.5, 'stiffness' => 0.4,
                    'stretch_weft' => 8, 'stretch_bias' => 20, 'recovery' => 78,
                    'transparency' => 0.55, 'sheen' => 0.35, 'roughness' => 0.6,
                    'shrinkage' => 1.5, 'breathability' => 0.7, 'warmth' => 0.3,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.2, 'slippage' => 0.35, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.6, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی ملایم', 'iron' => 'اتوی ملایم از پشت روی حوله', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'نواردوزی', 'tip' => 'همیشه با یک آستر ساده زیرش کار کنید تا نقش گیپور دیده شود.'],
                'description' => 'توری ضخیم با نقش برجسته؛ پارچه محبوب لباس عروس، کت مجلسی و آستین.',
            ],
            [
                'code' => 'lame',
                'name_fa' => 'لمه',
                'name_en' => 'Lamé',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 70], ['name' => 'الیاف فلزی', 'percent' => 30]],
                'profile' => [
                    'weight_gsm' => 130, 'thickness_mm' => 0.35, 'drape' => 0.5, 'stiffness' => 0.45,
                    'stretch_bias' => 15, 'recovery' => 70, 'transparency' => 0.1, 'sheen' => 1.0,
                    'roughness' => 0.4, 'shrinkage' => 1, 'breathability' => 0.15, 'warmth' => 0.45,
                    'moisture_absorption' => 0.03, 'wrinkle_resistance' => 0.6,
                    'fraying' => 0.7, 'slippage' => 0.6, 'distortion' => 0.4,
                    'heat_sensitivity' => 0.9, 'steam_sensitivity' => 0.8, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'خشک‌شویی؛ شست‌وشو براقی را می‌برد', 'iron' => 'اتو نکنید؛ حرارت الیاف فلزی را خراب می‌کند', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ نو و تیز', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'نواردوزی یا سردوز', 'tip' => 'پشت پارچه زبر است؛ برای بالاتنه آستر نرم بگذارید.'],
                'description' => 'پارچه براق فلزی برای لباس شب و مجلسی؛ زیبا اما به حرارت بسیار حساس.',
            ],

            // ——— مخمل، جیر و پارچه‌های خواب‌دار ———
            [
                'code' => 'velvet',
                'name_fa' => 'مخمل',
                'name_en' => 'Velvet',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 92], ['name' => 'الاستان', 'percent' => 8]],
                'profile' => [
                    'weight_gsm' => 285, 'thickness_mm' => 1.6, 'drape' => 0.6, 'stiffness' => 0.3,
                    'stretch_weft' => 22, 'stretch_bias' => 30, 'recovery' => 85,
                    'transparency' => 0.02, 'sheen' => 0.6, 'roughness' => 0.3,
                    'shrinkage' => 2, 'breathability' => 0.3, 'warmth' => 0.75,
                    'moisture_absorption' => 0.15, 'wrinkle_resistance' => 0.5,
                    'fraying' => 0.45, 'curling' => 0.2, 'slippage' => 0.6, 'distortion' => 0.5,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.75,
                    'has_nap' => true, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'خشک‌شویی یا شست‌وشوی دستی پشت‌ورو', 'iron' => 'اتو ممنوع؛ فقط بخار از پشت روی حوله مخمل', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۸۰/۱۲ نوک گرد', 'stitch' => 'کوک ۳ میلی‌متر با فشار پایه کم', 'seam' => 'سردوز', 'tip' => 'همه قطعات را با خواب پارچه در یک جهت (رو به پایین) بچینید تا رنگ یکسان دیده شود.'],
                'description' => 'پارچه پرزدار و درخشان؛ برای کت مجلسی، دامن، لباس شب و مانتو زمستانی. جهت خواب پارچه رنگ آن را عوض می‌کند.',
            ],
            [
                'code' => 'corduroy',
                'name_fa' => 'مخمل کبریتی',
                'name_en' => 'Corduroy',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 97], ['name' => 'الاستان', 'percent' => 3]],
                'profile' => [
                    'weight_gsm' => 320, 'thickness_mm' => 1.3, 'drape' => 0.25, 'stiffness' => 0.6,
                    'stretch_weft' => 12, 'stretch_bias' => 18, 'recovery' => 80,
                    'transparency' => 0.01, 'sheen' => 0.25, 'roughness' => 0.5,
                    'shrinkage' => 3.5, 'breathability' => 0.6, 'warmth' => 0.7,
                    'moisture_absorption' => 0.65, 'wrinkle_resistance' => 0.55,
                    'fraying' => 0.4, 'slippage' => 0.2, 'distortion' => 0.2,
                    'heat_sensitivity' => 0.3, 'steam_sensitivity' => 0.4,
                    'has_nap' => true, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین پشت‌ورو، آب ۳۰ درجه', 'iron' => 'اتو از پشت روی حوله', 'dryer' => 'ملایم'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک ۳ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'راه‌های کبریتی باید در همه قطعات هم‌جهت باشد.'],
                'description' => 'نخی راه‌راه پرزدار و گرم؛ برای شلوار، کت، دامن و لباس پاییزی.',
            ],
            [
                'code' => 'suede',
                'name_fa' => 'جیر',
                'name_en' => 'Microfiber Suede',
                'category' => 'synthetic',
                'family' => 'non_woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 265, 'thickness_mm' => 1.0, 'drape' => 0.35, 'stiffness' => 0.5,
                    'stretch_weft' => 10, 'stretch_bias' => 15, 'recovery' => 80,
                    'transparency' => 0.0, 'sheen' => 0.1, 'roughness' => 0.75,
                    'shrinkage' => 1, 'breathability' => 0.2, 'warmth' => 0.7,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.8,
                    'fraying' => 0.05, 'slippage' => 0.15, 'distortion' => 0.2,
                    'heat_sensitivity' => 0.65, 'steam_sensitivity' => 0.6,
                    'has_nap' => true, 'directional' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم با آب سرد', 'iron' => 'اتوی ملایم از پشت؛ اتوی مستقیم پرز را خواب می‌کند', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴', 'stitch' => 'کوک ۳ میلی‌متر', 'seam' => 'درز باز و پرس‌شده', 'tip' => 'سنجاق جای سوراخ می‌گذارد؛ با گیره یا سنجاق داخل جای دوخت کار کنید.'],
                'description' => 'شبه‌جیر مصنوعی با سطح مخملی؛ برای کت، جلیقه، دامن و کیف. لبه‌اش ریش نمی‌شود.',
            ],

            // ——— جین و پارچه‌های ساختارمند ———
            [
                'code' => 'denim',
                'name_fa' => 'جین',
                'name_en' => 'Denim',
                'category' => 'natural',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 340, 'thickness_mm' => 1.1, 'drape' => 0.12, 'stiffness' => 0.85,
                    'stretch_warp' => 0, 'stretch_weft' => 0, 'stretch_bias' => 10, 'recovery' => 45,
                    'transparency' => 0.0, 'sheen' => 0.1, 'roughness' => 0.6,
                    'shrinkage' => 5, 'breathability' => 0.55, 'warmth' => 0.6,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.6,
                    'fraying' => 0.5, 'slippage' => 0.08, 'distortion' => 0.1,
                    'heat_sensitivity' => 0.15, 'steam_sensitivity' => 0.1, 'directional' => true, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین پشت‌ورو با آب سرد تا رنگ نرود', 'iron' => 'اتوی داغ با بخار', 'dryer' => 'ملایم؛ آب می‌رود'],
                'sewing' => ['needle' => 'سوزن ۱۰۰/۱۶ مخصوص جین', 'stitch' => 'کوک ۳ تا ۳.۵ میلی‌متر', 'seam' => 'درز دوبل (فلت‌فل)', 'tip' => 'روی درزهای ضخیم از چکش یا انگشتی برای صاف کردن استفاده کنید و سرعت چرخ را کم بگیرید.'],
                'description' => 'نخی سنگین با بافت مورب؛ استاندارد شلوار، کت جین، دامن و پیش‌بند. اصلاً لخت نیست و فرم خودش را می‌سازد.',
            ],
            [
                'code' => 'denim-stretch',
                'name_fa' => 'جین کشی',
                'name_en' => 'Stretch Denim',
                'category' => 'blend',
                'family' => 'woven',
                'fibers' => [['name' => 'پنبه', 'percent' => 92], ['name' => 'پلی‌استر', 'percent' => 6], ['name' => 'الاستان', 'percent' => 2]],
                'profile' => [
                    'weight_gsm' => 320, 'thickness_mm' => 1.0, 'drape' => 0.2, 'stiffness' => 0.7,
                    'stretch_weft' => 25, 'stretch_bias' => 30, 'recovery' => 90,
                    'transparency' => 0.0, 'sheen' => 0.12, 'roughness' => 0.55,
                    'shrinkage' => 3, 'breathability' => 0.5, 'warmth' => 0.6,
                    'moisture_absorption' => 0.6, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.45, 'slippage' => 0.1, 'distortion' => 0.15,
                    'heat_sensitivity' => 0.3, 'steam_sensitivity' => 0.2, 'directional' => true, 'pressing' => 'high',
                ],
                'care' => ['wash' => 'ماشین پشت‌ورو با آب سرد', 'iron' => 'اتوی متوسط؛ حرارت زیاد کشسانی را از بین می‌برد', 'dryer' => 'دمای کم'],
                'sewing' => ['needle' => 'سوزن ۹۰/۱۴ کشی', 'stitch' => 'کوک ۳ میلی‌متر', 'seam' => 'سردوز و درز دوبل', 'tip' => 'کشسانی ۲۵ درصدی دارد؛ الگو را دو تا سه سانتی‌متر تنگ‌تر بگیرید.'],
                'description' => 'جین با الاستان؛ راحتی شلوار چسبان را می‌دهد و فرم بدن را نگه می‌دارد.',
            ],

            // ——— کشباف‌ها (تریکو) ———
            [
                'code' => 'jersey',
                'name_fa' => 'جرسی (تریکو)',
                'name_en' => 'Single Jersey',
                'category' => 'natural',
                'family' => 'knit',
                'fibers' => [['name' => 'پنبه', 'percent' => 95], ['name' => 'الاستان', 'percent' => 5]],
                'profile' => [
                    'weight_gsm' => 180, 'thickness_mm' => 0.7, 'drape' => 0.6, 'stiffness' => 0.2,
                    'stretch_warp' => 15, 'stretch_weft' => 50, 'stretch_bias' => 45, 'recovery' => 90,
                    'transparency' => 0.1, 'sheen' => 0.15, 'roughness' => 0.25,
                    'shrinkage' => 4, 'breathability' => 0.85, 'warmth' => 0.45,
                    'moisture_absorption' => 0.75, 'wrinkle_resistance' => 0.65,
                    'fraying' => 0.05, 'curling' => 0.75, 'slippage' => 0.35, 'distortion' => 0.5,
                    'heat_sensitivity' => 0.25, 'steam_sensitivity' => 0.2, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی ملایم بدون کشیدن پارچه', 'dryer' => 'دمای کم؛ آب می‌رود'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۵/۱۱ نوک گرد', 'stitch' => 'کوک کشی یا زیگزاگ باریک', 'seam' => 'سردوز', 'tip' => 'لبه‌ها لوله می‌شود؛ پیش از دوخت با لایی نواری تثبیت کنید و شانه‌ها را با نوار محکم کنید.'],
                'description' => 'کشباف پایه تی‌شرت و لباس راحتی؛ کشسانی عرضی زیاد، بدون ریش‌شدن، بدون نیاز به پنس.',
            ],
            [
                'code' => 'cotton-lycra',
                'name_fa' => 'نخی کشی (پنبه-الاستان)',
                'name_en' => 'Cotton Lycra',
                'category' => 'blend',
                'family' => 'knit',
                'fibers' => [['name' => 'پنبه', 'percent' => 90], ['name' => 'الاستان', 'percent' => 10]],
                'profile' => [
                    'weight_gsm' => 205, 'thickness_mm' => 0.8, 'drape' => 0.55, 'stiffness' => 0.2,
                    'stretch_warp' => 25, 'stretch_weft' => 60, 'stretch_bias' => 55, 'recovery' => 92,
                    'transparency' => 0.08, 'sheen' => 0.2, 'roughness' => 0.2,
                    'shrinkage' => 3.5, 'breathability' => 0.8, 'warmth' => 0.5,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.7,
                    'fraying' => 0.05, 'curling' => 0.5, 'slippage' => 0.3, 'distortion' => 0.45,
                    'heat_sensitivity' => 0.4, 'steam_sensitivity' => 0.3, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'دمای کم'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۵/۱۱', 'stitch' => 'کوک کشی ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'آزادی منفی بدهید؛ لباس باید کمی کوچک‌تر از بدن بریده شود.'],
                'description' => 'کشباف پرکشسان و برگشت‌پذیر؛ برای تی‌شرت چسبان، لگ، ساپورت و لباس ورزشی.',
            ],
            [
                'code' => 'rib-knit',
                'name_fa' => 'کشباف ریب',
                'name_en' => 'Rib Knit',
                'category' => 'blend',
                'family' => 'knit',
                'fibers' => [['name' => 'پنبه', 'percent' => 95], ['name' => 'الاستان', 'percent' => 5]],
                'profile' => [
                    'weight_gsm' => 230, 'thickness_mm' => 1.0, 'drape' => 0.45, 'stiffness' => 0.25,
                    'stretch_warp' => 25, 'stretch_weft' => 85, 'stretch_bias' => 60, 'recovery' => 92,
                    'transparency' => 0.06, 'sheen' => 0.15, 'roughness' => 0.35,
                    'shrinkage' => 4, 'breathability' => 0.8, 'warmth' => 0.6,
                    'moisture_absorption' => 0.7, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.05, 'curling' => 0.3, 'slippage' => 0.25, 'distortion' => 0.4,
                    'heat_sensitivity' => 0.35, 'steam_sensitivity' => 0.3, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'دمای کم'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۵/۱۱', 'stitch' => 'کوک کشی', 'seam' => 'سردوز', 'tip' => 'انتخاب اول برای مچ، یقه و کمر کشی؛ به اندازه سه‌چهارم محیط ببرید تا جمع کند.'],
                'description' => 'کشباف راه‌راه با کشسانی بسیار زیاد؛ برای مچ آستین، یقه، کمر و بلوز چسبان.',
            ],
            [
                'code' => 'french-terry',
                'name_fa' => 'فوتر',
                'name_en' => 'French Terry',
                'category' => 'natural',
                'family' => 'knit',
                'fibers' => [['name' => 'پنبه', 'percent' => 80], ['name' => 'پلی‌استر', 'percent' => 18], ['name' => 'الاستان', 'percent' => 2]],
                'profile' => [
                    'weight_gsm' => 290, 'thickness_mm' => 1.5, 'drape' => 0.15, 'stiffness' => 0.45,
                    'stretch_warp' => 10, 'stretch_weft' => 30, 'stretch_bias' => 25, 'recovery' => 85,
                    'transparency' => 0.0, 'sheen' => 0.08, 'roughness' => 0.4,
                    'shrinkage' => 5, 'breathability' => 0.7, 'warmth' => 0.8,
                    'moisture_absorption' => 0.75, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.08, 'curling' => 0.35, 'slippage' => 0.15, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.3, 'steam_sensitivity' => 0.25, 'has_nap' => true, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین پشت‌ورو، آب ۳۰ درجه', 'iron' => 'اتوی ملایم از پشت', 'dryer' => 'دمای کم؛ حتماً پیش‌شور کنید'],
                'sewing' => ['needle' => 'سوزن جرسی ۸۰/۱۲', 'stitch' => 'کوک کشی ۳ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'ضخیم و ایستاست؛ برای هودی و سویشرت با آزادی زیاد الگو بزنید.'],
                'description' => 'کشباف ضخیم با پشت حوله‌ای؛ پارچه هودی، سویشرت و شلوار راحتی. ریزش کمی دارد و حجم می‌دهد.',
            ],
            [
                'code' => 'jerse',
                'name_fa' => 'ژرسه',
                'name_en' => 'Jersey Crepe',
                'category' => 'synthetic',
                'family' => 'knit',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 94], ['name' => 'الاستان', 'percent' => 6]],
                'profile' => [
                    'weight_gsm' => 150, 'thickness_mm' => 0.5, 'drape' => 0.75, 'stiffness' => 0.15,
                    'stretch_warp' => 12, 'stretch_weft' => 35, 'stretch_bias' => 40, 'recovery' => 88,
                    'transparency' => 0.18, 'sheen' => 0.25, 'roughness' => 0.3,
                    'shrinkage' => 1.5, 'breathability' => 0.4, 'warmth' => 0.4,
                    'moisture_absorption' => 0.12, 'wrinkle_resistance' => 0.9,
                    'fraying' => 0.1, 'curling' => 0.5, 'slippage' => 0.4, 'distortion' => 0.45,
                    'heat_sensitivity' => 0.7, 'steam_sensitivity' => 0.5, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۰/۱۰', 'stitch' => 'کوک کشی باریک', 'seam' => 'سردوز', 'tip' => 'عالی برای لباس‌های دراپه و گره‌دار؛ الگو را با آزادی کم ببرید.'],
                'description' => 'کشباف نازک و لخت با سطح کرپ؛ برای مانتو تابستانی، پیراهن دراپه و شال. تقریباً چین نمی‌خورد.',
            ],
            [
                'code' => 'acrylic-knit',
                'name_fa' => 'آکریلیک',
                'name_en' => 'Acrylic Knit',
                'category' => 'synthetic',
                'family' => 'knit',
                'fibers' => [['name' => 'آکریلیک', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 255, 'thickness_mm' => 1.3, 'drape' => 0.55, 'stiffness' => 0.2,
                    'stretch_warp' => 15, 'stretch_weft' => 30, 'stretch_bias' => 35, 'recovery' => 78,
                    'transparency' => 0.08, 'sheen' => 0.2, 'roughness' => 0.35,
                    'shrinkage' => 2, 'breathability' => 0.35, 'warmth' => 0.85,
                    'moisture_absorption' => 0.08, 'wrinkle_resistance' => 0.75,
                    'fraying' => 0.1, 'curling' => 0.45, 'slippage' => 0.3, 'distortion' => 0.5,
                    'heat_sensitivity' => 0.8, 'steam_sensitivity' => 0.6, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم با آب سرد', 'iron' => 'اتوی خیلی ملایم؛ حرارت زیاد پرز را ذوب می‌کند', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن جرسی ۸۰/۱۲', 'stitch' => 'کوک کشی', 'seam' => 'سردوز', 'tip' => 'جانشین ارزان پشم است اما گلوله می‌کند؛ برای لباس روزمره خوب است.'],
                'description' => 'کشباف گرم و سبک شبیه پشم؛ برای پلیور، شال و لباس زمستانی ارزان.',
            ],
            [
                'code' => 'modal',
                'name_fa' => 'مودال',
                'name_en' => 'Modal',
                'category' => 'synthetic',
                'family' => 'knit',
                'fibers' => [['name' => 'مودال', 'percent' => 92], ['name' => 'الاستان', 'percent' => 8]],
                'profile' => [
                    'weight_gsm' => 160, 'thickness_mm' => 0.55, 'drape' => 0.85, 'stiffness' => 0.12,
                    'stretch_warp' => 18, 'stretch_weft' => 40, 'stretch_bias' => 45, 'recovery' => 88,
                    'transparency' => 0.15, 'sheen' => 0.45, 'roughness' => 0.05,
                    'shrinkage' => 3, 'breathability' => 0.8, 'warmth' => 0.4,
                    'moisture_absorption' => 0.85, 'wrinkle_resistance' => 0.65,
                    'fraying' => 0.08, 'curling' => 0.6, 'slippage' => 0.5, 'distortion' => 0.5,
                    'heat_sensitivity' => 0.45, 'steam_sensitivity' => 0.4, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی ملایم', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن جرسی ۷۰/۱۰', 'stitch' => 'کوک کشی باریک', 'seam' => 'سردوز', 'tip' => 'بسیار لخت و لیز است؛ روی میز پهن برش بزنید تا از لبه آویزان نشود.'],
                'description' => 'کشباف بسیار نرم و لخت با درخشش ملایم؛ برای تی‌شرت لوکس، لباس زیر و پیراهن راحتی.',
            ],
            [
                'code' => 'elastane-jersey',
                'name_fa' => 'الاستان (اسپندکس)',
                'name_en' => 'Elastane Jersey',
                'category' => 'synthetic',
                'family' => 'knit',
                'fibers' => [['name' => 'پلی‌آمید', 'percent' => 80], ['name' => 'الاستان', 'percent' => 20]],
                'profile' => [
                    'weight_gsm' => 200, 'thickness_mm' => 0.7, 'drape' => 0.5, 'stiffness' => 0.2,
                    'stretch_warp' => 60, 'stretch_weft' => 120, 'stretch_bias' => 110, 'recovery' => 95,
                    'transparency' => 0.1, 'sheen' => 0.4, 'roughness' => 0.15,
                    'shrinkage' => 1, 'breathability' => 0.35, 'warmth' => 0.45,
                    'moisture_absorption' => 0.08, 'wrinkle_resistance' => 0.9,
                    'fraying' => 0.05, 'curling' => 0.4, 'slippage' => 0.35, 'distortion' => 0.6,
                    'heat_sensitivity' => 0.85, 'steam_sensitivity' => 0.7, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم با آب سرد و بدون نرم‌کننده', 'iron' => 'اتو نکنید؛ حرارت کشسانی را می‌کشد', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۵/۱۱ کشی', 'stitch' => 'کوک کشی سه‌سوزنه یا زیگزاگ', 'seam' => 'سردوز با نخ کشی', 'tip' => 'الگو را ۱۰ تا ۲۰ درصد کوچک‌تر از اندازه بدن ببرید (آزادی منفی).'],
                'description' => 'پرکشسان‌ترین پارچه؛ برای لباس شنا، لباس ورزشی، ساپورت و لباس رقص.',
            ],

            // ——— الیاف مصنوعی تاری-پودی ———
            [
                'code' => 'polyester-plain',
                'name_fa' => 'پلی‌استر ساده',
                'name_en' => 'Polyester',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 125, 'thickness_mm' => 0.35, 'drape' => 0.55, 'stiffness' => 0.3,
                    'stretch_bias' => 15, 'recovery' => 80, 'transparency' => 0.12, 'sheen' => 0.35,
                    'roughness' => 0.3, 'shrinkage' => 1, 'breathability' => 0.25, 'warmth' => 0.4,
                    'moisture_absorption' => 0.08, 'wrinkle_resistance' => 0.9,
                    'fraying' => 0.5, 'slippage' => 0.45, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.75, 'steam_sensitivity' => 0.55, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین، آب ۴۰ درجه', 'iron' => 'اتوی ملایم؛ حرارت زیاد سوراخ می‌کند', 'dryer' => 'دمای کم'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ یا ۸۰/۱۲', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'اصلاً چین نمی‌خورد اما نفس نمی‌کشد؛ برای زیر لباس مناسب نیست.'],
                'description' => 'پارچه مصنوعی ارزان و بادوام؛ برای لباس فرم، پرده، کیف و کارهای تزئینی.',
            ],
            [
                'code' => 'nylon',
                'name_fa' => 'نایلون',
                'name_en' => 'Nylon',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'نایلون (پلی‌آمید)', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 90, 'thickness_mm' => 0.25, 'drape' => 0.5, 'stiffness' => 0.35,
                    'stretch_bias' => 18, 'recovery' => 88, 'transparency' => 0.2, 'sheen' => 0.5,
                    'roughness' => 0.2, 'shrinkage' => 1, 'breathability' => 0.2, 'warmth' => 0.45,
                    'moisture_absorption' => 0.1, 'wrinkle_resistance' => 0.85,
                    'fraying' => 0.55, 'slippage' => 0.6, 'distortion' => 0.35,
                    'heat_sensitivity' => 0.85, 'steam_sensitivity' => 0.7, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'ماشین ملایم با آب سرد', 'iron' => 'اتوی خیلی ملایم یا بدون اتو', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ میکروتکس', 'stitch' => 'کوک ۲ میلی‌متر', 'seam' => 'درز فرانسوی یا سردوز ریز', 'tip' => 'به حرارت بسیار حساس است؛ دمای اتو را روی کمترین درجه بگذارید.'],
                'description' => 'سبک، محکم و آب‌گریز؛ برای بادگیر، آستر کاپشن، کیف و لباس ورزشی.',
            ],
            [
                'code' => 'viscose',
                'name_fa' => 'ویسکوز (ریون)',
                'name_en' => 'Viscose / Rayon',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'ویسکوز', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 130, 'thickness_mm' => 0.35, 'drape' => 0.82, 'stiffness' => 0.15,
                    'stretch_bias' => 22, 'recovery' => 55, 'transparency' => 0.2, 'sheen' => 0.4,
                    'roughness' => 0.15, 'shrinkage' => 6, 'breathability' => 0.75, 'warmth' => 0.3,
                    'moisture_absorption' => 0.8, 'wrinkle_resistance' => 0.3,
                    'fraying' => 0.55, 'slippage' => 0.55, 'distortion' => 0.45,
                    'heat_sensitivity' => 0.4, 'steam_sensitivity' => 0.35, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'شست‌وشوی دستی یا ماشین ملایم با آب سرد', 'iron' => 'اتوی متوسط از پشت', 'dryer' => 'خشک‌کن ممنوع؛ آب‌رفت زیاد'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'حتماً پیش‌شور کنید؛ تا ۶ درصد آب می‌رود.'],
                'description' => 'ریزش نرم و لمس خنک شبیه ابریشم با قیمت کم؛ برای پیراهن، مانتو تابستانی و شال. آب‌رفت بالا دارد.',
            ],
            [
                'code' => 'lyocell',
                'name_fa' => 'لیوسل (تنسل)',
                'name_en' => 'Lyocell / Tencel',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'لیوسل', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 150, 'thickness_mm' => 0.4, 'drape' => 0.78, 'stiffness' => 0.2,
                    'stretch_bias' => 20, 'recovery' => 70, 'transparency' => 0.1, 'sheen' => 0.4,
                    'roughness' => 0.1, 'shrinkage' => 3, 'breathability' => 0.85, 'warmth' => 0.35,
                    'moisture_absorption' => 0.85, 'wrinkle_resistance' => 0.55,
                    'fraying' => 0.45, 'slippage' => 0.45, 'distortion' => 0.3,
                    'heat_sensitivity' => 0.35, 'steam_sensitivity' => 0.3, 'pressing' => 'medium',
                ],
                'care' => ['wash' => 'ماشین ملایم، آب ۳۰ درجه', 'iron' => 'اتوی متوسط', 'dryer' => 'دمای کم'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰', 'stitch' => 'کوک ۲.۵ میلی‌متر', 'seam' => 'سردوز', 'tip' => 'نسخه پایدارتر و کم‌آب‌رفت‌تر ویسکوز است.'],
                'description' => 'الیاف چوب با ریزش نرم، خنکی بالا و دوستدار پوست؛ برای پیراهن، شلوار راحتی و ملحفه.',
            ],
            [
                'code' => 'lining-poly',
                'name_fa' => 'آستری',
                'name_en' => 'Lining',
                'category' => 'synthetic',
                'family' => 'woven',
                'fibers' => [['name' => 'پلی‌استر', 'percent' => 100]],
                'profile' => [
                    'weight_gsm' => 70, 'thickness_mm' => 0.16, 'drape' => 0.75, 'stiffness' => 0.2,
                    'stretch_bias' => 20, 'recovery' => 78, 'transparency' => 0.25, 'sheen' => 0.6,
                    'roughness' => 0.05, 'shrinkage' => 1.5, 'breathability' => 0.25, 'warmth' => 0.3,
                    'moisture_absorption' => 0.08, 'wrinkle_resistance' => 0.8,
                    'fraying' => 0.65, 'slippage' => 0.85, 'distortion' => 0.4,
                    'heat_sensitivity' => 0.8, 'steam_sensitivity' => 0.6, 'pressing' => 'low',
                ],
                'care' => ['wash' => 'همراه لباس اصلی با آب سرد', 'iron' => 'اتوی خیلی ملایم', 'dryer' => 'خشک‌کن ممنوع'],
                'sewing' => ['needle' => 'سوزن ۷۰/۱۰ میکروتکس', 'stitch' => 'کوک ۲.۲ میلی‌متر', 'seam' => 'سردوز ریز', 'tip' => 'آستر را همیشه کمی گشادتر از رویه ببرید تا لباس را نکشد.'],
                'description' => 'آستر لیز و سبک برای کت، مانتو، دامن و لباس مجلسی؛ لباس را روی بدن روان می‌کند.',
            ],
        ];
    }
}
